image: Visual Studio 2017

configuration:
  - Release

environment:
  MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
  MSVC_SETUP_ARG: x64

install:
  #############################################################################
  # Setup Ninja and CMake dependencies
  #############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  # Setup Ninja
  - set NINJA_URL=https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip
  - appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version

before_build:
  #############################################################################
  # Setup MSVC Environment
  #############################################################################
  - call "%MSVC_SETUP_PATH%" %MSVC_SETUP_ARG%
  - cd %APPVEYOR_BUILD_FOLDER%
  
build_script:
  - cmake -G Ninja
    "-DCMAKE_BUILD_TYPE=%configuration%"
    %APPVEYOR_BUILD_FOLDER%

  #############################################################################
  # Build Step
  - ninja
#  - ninja check-all # I wouldn't sweat a few failures here. This step is optional
#  - ninja install
